---
- name: Append message to files shell script
  hosts: localhost
  gather_facts: no
  vars:
    script_path: "./create_dynamic_files.sh"
    target_directory: "results"
    message_to_append: "Hello its LeadBlackTech"
    file_name: "html,yaml,json"

  tasks:
    - name: Execute the script to append message to files
      shell: "'./create_dynamic_files.sh' '{{ target_directory }}' '{{ message_to_append }}' '{{ item }}'" #needs work
      loop: "{{ file_name.split(',') }}"
      args:
        executable: /bin/bash
      run_once: true


# will integrate this script with the previous
# script to create dynamic files
# and append message to them
# Will modify this code to take ansible survey vars as input for the message to append
# will modifyy this code to take ansible prompt vars as input for the message to append